{% set name = "cellpy" %}
{% set version = "1.0.0.post9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80a4121e29e59d11b8a05a87654800aa2a11a002454a52da5c4d8be137418864

build:
  noarch: python
  number: 1
  entry_points:
    - cellpy=cellpy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9, <3.12
    - pip >=20.0.2
    - setuptools >=38.6.0
  run:
    - python >=3.9, <3.12
    - pip >=23.1.2
    - numpy >=1.24.3
    - openpyxl >=3.1.1
    - xlrd >=2.0.1
    - matplotlib-base >=3.7.1
    - cryptography >=40.0.2
    - click >=8.1.3
    - scipy >=1.10.1
    - pandas >=2.0.1
    - setuptools >=67.7.2
    - ruamel.yaml >=0.17.21
    - pyodbc >=4.0.39
    - cookiecutter >=2.1.1
    - tqdm >=4.65.0
    - lmfit >=1.2.0
    - hdf5 >=1.14.0
    - pytables >=3.8.0
    - python-box >=7.0.1
    - pint >=0.20.1
    - sqlalchemy >=2.0.11
    - python-dotenv >=1.0.0
    - fabric >=3.0.0
    - rich >=13.5.1
    - dateparser >=1.1.8

test:
  imports:
    - cellpy
  commands:
    - cellpy --help

about:
  home: https://github.com/jepegit/cellpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extract and manipulate data from different battery cell testers.
  description: |
    Extract and manipulate data from different battery cell testers.
  doc_url: https://cellpy.readthedocs.io/
  dev_url: https://github.com/jepegit/cellpy

extra:
  recipe-maintainers:
    - jepegit
