{% set name = "cellpy" %}
{% set version = "1.0.1a6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e72ca88a60e3e00ae67f6253c5a795edbb1b0f8868d2053540fa43a657003707

build:
  noarch: python
  number: 0
  entry_points:
    - cellpy=cellpy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9, <3.12
    - pip >=20.0.2
    - setuptools >=38.6.0
  run:
    - python >=3.9, <3.12
    - click >=8.1.7
    - cookiecutter >=2.5.0
    - cryptography >=42.0.2
    - dateparser >=1.2.0
    - fabric >=3.2.2
    - hdf5 >=1.14.3
    - lmfit >=1.2.2
    - matplotlib-base >=3.8.2
    - numpy >=1.26.3
    - openpyxl >=3.1.2
    - pandas >=2.2.0
    - pint >=0.23
    - pip >=24.0
    - pyodbc >=5.0.1
    - pytables >=3.9.2
    - python-box >=7.1.1
    - python-dotenv >=1.0.1
    - rich >=13.7.0
    - ruamel.yaml >=0.18.5
    - scipy >=1.12.0
    - setuptools >=69.0.3
    - sqlalchemy >=2.0.25
    - tqdm >=4.66.1
    - xlrd >=2.0.1
    - ipykernel >=6.29.0
    - ipython >=8.21.0
    - ipywidgets >=8.1.1
    - plotly >=5.18.0
    - pygithub >=2.2.0
    - __win
    - sqlalchemy-access >=2.0.2

test:
  imports:
    - cellpy
  commands:
    - cellpy --help

about:
  home: https://github.com/jepegit/cellpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extract and manipulate data from different battery cell testers.
  description: |
    Extract and manipulate data from different battery cell testers.
  doc_url: https://cellpy.readthedocs.io/
  dev_url: https://github.com/jepegit/cellpy

extra:
  recipe-maintainers:
    - jepegit
