{% set name = "cellpy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12802387ee239352e3313ba9cadbe637ead1d125d11ec2218d84fa937441271d

build:
  noarch: python
  number: 0
  entry_points:
    - cellpy=cellpy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip >=20.0.2
    - setuptools >=38.6.0
  run:
    - python >=3.8
    - numpy >=1.15
    - openpyxl >=3.0.5
    - matplotlib-base >=3.1.3
    - cryptography >=2.8
    - click >=7.1.1
    - scipy >=1.4.1
    - pandas >=1.0
    - sqlalchemy >=1.4
    - setuptools >=38.6.0
    - ruamel.yaml >=0.15.87
    - pyodbc >=4.0.16
    - PyGithub >=1.43.6
    - cookiecutter >=1.7.0
    - tqdm >=4.44.1
    - ipython >=7.13.0
    - ipywidgets >=7.5.1
    - lmfit >=1.0.0
    - ipykernel >=5.1.4
    - pytables >=3.6.1
    - python-box >=4.2.2
    - sqlalchemy <=1.4.46

test:
  imports:
    - cellpy
  commands:
    - cellpy --help

about:
  home: https://github.com/jepegit/cellpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extract and manipulate data from different battery cell testers.
  description: |
    Extract and manipulate data from different battery cell testers.
  doc_url: https://cellpy.readthedocs.io/
  dev_url: https://github.com/jepegit/cellpy

extra:
  recipe-maintainers:
    - jepegit
