{% set name = "cellpy" %}
{% set version = "1.0.0.post7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ce753923c21984e7113206ae8e34e5ffd65090847d75df2a5cd80dde93cbe52

build:
  noarch: python
  number: 0
  entry_points:
    - cellpy=cellpy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9, <3.12
    - pip >=20.0.2
    - setuptools >=38.6.0
  run:
    - python >=3.9, <3.12
    - PyGithub
    - click>=8.1.3
    - cookiecutter>=2.1.1
    - coverage>=7.2.3
    - cryptography>=40.0.2
    - dateparser>=1.1.8
    - fabric>=3.0.0
    - hdf5>=1.14.0
    - lmfit>=1.2.0
    - matplotlib>=3.7.1
    - numpy>=1.24.3
    - openpyxl>=3.1.1
    - pandas>=2.0.1
    - pint>=0.20.1
    - pip>=23.1.2
    - pyodbc>=4.0.39
    - pytables>=3.8.0
    - pytest>=7.3.1
    - pytest-benchmark>=4.0.0
    - pytest-timeout>=2.1.0
    - python-box>=7.0.1
    - python-dotenv>=1.0.0
    - python>=3.9
    - rich>=13.5.1
    - ruamel.yaml>=0.17.21
    - scipy>=1.10.1
    - setuptools>=67.7.2
    - sqlalchemy>=2.0.11
    - tqdm>=4.65.0
    - xlrd>=2.0.1

test:
  imports:
    - cellpy
  commands:
    - cellpy --help


about:
  home: https://github.com/jepegit/cellpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extract and manipulate data from different battery cell testers.
  description: |
    Extract and manipulate data from different battery cell testers.
  doc_url: https://cellpy.readthedocs.io/
  dev_url: https://github.com/jepegit/cellpy

extra:
  recipe-maintainers:
    - jepegit
