conda_forge_output_validation: true
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  win_64: appveyor
noarch_platforms:
  - linux_64
  - win_64