build_platform:
  linux_64: linux_64
  win_64: win_64
conda_forge_output_validation: true
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
